### ISSUE TITLE
对比时样式有错位

### ISSUE THREAD

**Issue by FlyingFishPeng** [ddchef/vue-code-diff#11]
![企业微信截图_15668244031919](https://user-images.githubusercontent.com/27657307/63692534-7a7f3880-c844-11e9-9020-f5ed26c384d8.png)

**Comment by ddchef** [comment]
这个是左边没有代码，导致的吗？

**Comment by FlyingFishPeng** [comment]
> 这个是左边没有代码，导致的吗？

是的哈。有时候左边有代码的时候，左边的顶部也会有空白，跟右边的行号对不齐

**Comment by VincyLu** [comment]
请问输入两个字符串，能想json一样格式化吗

**Comment by grtan** [comment]
> > 这个是左边没有代码，导致的吗？
> 
> 是的哈。有时候左边有代码的时候，左边的顶部也会有空白，跟右边的行号对不齐

这是因为.d2h-code-side-linenumber用了绝对定位，而没有设置top之类的属性，导致页面滚动时行号那一列都跟着滚动，可以修正如下

.d2h-code-side-linenumber {
    position: static;
}

.d2h-code-side-line {
    margin-left: 0;
}
