### ISSUE TITLE
Absolutely positioned line numbers overflowing container

### ISSUE THREAD

**Issue by jasonford** [ddchef/vue-code-diff#40]
![Screenshot_from_2021-02-05_17-27-26](https://user-images.githubusercontent.com/1317275/107207622-2ef52600-6a09-11eb-9796-7ae00ade6fe5.png)

This issue is probably upstream, but figured I'd open it here since it can be patched with a simple:

```
.d2h-wrapper
{
  position: relative;
}
```

For extra context: the overflow happens because the line numbers stay in the same location within the scroll window when a parent of your components scrolls.

**Comment by ddchef** [comment]
thanks,I fixed it
