### ISSUE TITLE
vue-code-diff@1.0.0 只显示1000行

### ISSUE THREAD

**Issue by jzsn2018** [ddchef/vue-code-diff#42]
vue-code-diff@1.0.0 只显示1000行数据，超出的数据不显示了

**Comment by ddchef** [comment]
测试过，没有发现改问题

**Comment by jzsn2018** [comment]
> 测试过，没有发现该问题

我知道原因了,是因为插件只展示有差异的部分,对于公共的部分你直接隐藏掉了

**Comment by FroYo-User** [comment]
为什么我用这个插件返回两个json字符串 做比较只展示一行
