### ISSUE TITLE
[bug] The height of TD tag with content is different from that of TD tag without content

### ISSUE THREAD

**Issue by microkof** [ddchef/vue-code-diff#45]
You can see this:
![image](https://user-images.githubusercontent.com/5286586/111971440-51657d80-8b37-11eb-9214-606c34469945.png)

The height of TD tag in left section is 19px, and right one is 17px.

**Comment by ddchef** [comment]
version？

**Comment by microkof** [comment]
> version？

Specifically referring to demo page http://diff.xjie.me

**Comment by robbylucia** [comment]
> version？

For me I am using "vue-code-diff": "^1.1.0"
and I have this issue.
